//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tren3_4_Makarov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Izmeren_id { get; set; }
        public Nullable<decimal> Ostatok { get; set; }
        public Nullable<int> Sklad_id { get; set; }
    
        public virtual Ed_Izmeren Ed_Izmeren { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
